#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  4 20:54:17 2022

@author: pikachu
"""

import matplotlib.pyplot as plt
import random
import pprint
import pandas as pd

result = {}
temp_res = []


'''random guessing'''
for i in range(100):
    low = 1
    high = 100
    ans = random.randint(low, high)
    #print('answer is ' +str(ans))
    
    for j in range(1, 99):
        if j == 1:    
            guess = 50
        else:
            guess = random.randint(low, high)
        #print(guess)
        if ans == guess:
            temp_res.append(j)
            #print('You get it!')
            
            break
        
        else:
            
            if guess > ans:
                high = guess-1
            else:
                low = guess+1
    
        #print('range is ' + str(low) +' to ' + str(high))
                
for num in temp_res:
    result.setdefault(num, 0)
    result[num] +=1
    

'''data_frame'''
#df = pd.DataFrame([result])
df = pd.DataFrame(list(result.items()), columns= ['guess_times', 'value'])
df.sort_values(by=['guess_times'], inplace=True)


'''plot'''

fig = plt.figure(figsize=(10,7),dpi=80, facecolor='w', edgecolor='w')
plt.bar(df.guess_times, height=df.value)
plt.title('Guessing number', fontsize=15)
plt.xlabel("Guess_times",fontsize=13)
plt.ylabel("Value",fontsize=13)
plt.show()
               
                
            
         
    
    